#!/bin/bash

rm -rf output
nmap  $1 > tmp
mkdir output
cp tmp $1_nmap_ports.txt
mv $1_nmap_ports.txt output
grep /tcp tmp > tmp2
sed -i "s/\/tcp.*//" tmp2
mv tmp2 output/portlist.txt
rm tmp
cat output/portlist.txt