#!/bin/bash

nmap -T5 -sV --script=vulscan/vulscan.nse $1 > vuln_output.txt
cp vuln_output.txt output/vuln_output.txt
mv vuln_output.txt tmpV
egrep \[[0-9]+\] tmpV > tmpV1
rm tmpV
mv tmpV1 output/$1_vulnerabilities.txt 
cat output/$1_vulnerabilities.txt

